name: Deploy Angular CV to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app (mycv) with correct baseHref
        run: npm run build -- --configuration production --base-href "/mycv/"

      - name: Copy built files to docs/
        run: |
          rm -rf docs
          mkdir docs
          cp -r dist/mycv/browser/* docs/

      - name: Commit and push docs
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "ci@example.com"
          git add docs
          git commit -m "Auto-deploy to docs from main" || echo "No changes to commit"
          git push
